In [1]:
from shrinkbench.plot import df_from_results, plot_df

In [2]:
df = df_from_results('final_results/results_resnet56')

In [3]:
df

,dataset,model,strategy,compression,size,size_nz,real_compression,flops,flops_nz,speedup,...,pre_acc5,post_acc1,post_acc5,seed,batch_size,epochs,optim,lr,completed_epochs,path
9,CIFAR10,resnet56,GlobalCausalPruning,2,853018,428866,1.989008,125485696,68729536.0,1.825790,...,0.488281,0.902930,0.973828,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-100808...
3,CIFAR10,resnet56,GlobalCausalPruning,4,853018,216790,3.934766,125485696,41535808.0,3.021145,...,0.488281,0.876465,0.972852,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-102733...
10,CIFAR10,resnet56,GlobalCausalPruning,8,853018,110752,7.702055,125485696,18676288.0,6.718985,...,0.488281,0.800586,0.968262,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-104952...
2,CIFAR10,resnet56,GlobalCausalPruning,16,853018,57734,14.774968,125485696,7706240.0,16.283648,...,0.488477,0.733691,0.962793,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-111150...
11,CIFAR10,resnet56,GlobalCausalPruning,32,853018,31223,27.320181,125485696,4825472.0,26.004854,...,0.488281,0.722266,0.961328,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-113332...
6,CIFAR10,resnet56,GlobalCausalPruning,64,853018,17969,47.471646,125485696,1951232.0,64.311008,...,0.488281,0.628809,0.947363,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-115437...
7,CIFAR10,resnet56,GlobalMagWeight,2,853018,426509,2.000000,125485696,68716352.0,1.826140,...,0.973047,0.912891,0.974219,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-120048...
5,CIFAR10,resnet56,GlobalMagWeight,4,853018,213255,3.999991,125485696,39178560.0,3.202918,...,0.945508,0.907520,0.974707,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-120702...
1,CIFAR10,resnet56,GlobalMagWeight,8,853018,106628,7.999944,125485696,22508480.0,5.575041,...,0.643652,0.895215,0.974512,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-121316...
8,CIFAR10,resnet56,GlobalMagWeight,16,853018,53314,15.999887,125485696,12930688.0,9.704487,...,0.516797,0.868066,0.973730,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-121928...
4,CIFAR10,resnet56,GlobalMagWeight,32,853018,26657,31.999775,125485696,7275008.0,17.248874,...,0.488281,0.815430,0.969629,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-122541...
0,CIFAR10,resnet56,GlobalMagWeight,64,853018,13329,63.997149,125485696,3658176.0,34.302804,...,0.490918,0.702832,0.960254,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-123154...

In [4]:
MODEL = 'resnet56'

df = df[df['model'] == MODEL]

In [5]:
df

,dataset,model,strategy,compression,size,size_nz,real_compression,flops,flops_nz,speedup,...,pre_acc5,post_acc1,post_acc5,seed,batch_size,epochs,optim,lr,completed_epochs,path
9,CIFAR10,resnet56,GlobalCausalPruning,2,853018,428866,1.989008,125485696,68729536.0,1.825790,...,0.488281,0.902930,0.973828,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-100808...
3,CIFAR10,resnet56,GlobalCausalPruning,4,853018,216790,3.934766,125485696,41535808.0,3.021145,...,0.488281,0.876465,0.972852,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-102733...
10,CIFAR10,resnet56,GlobalCausalPruning,8,853018,110752,7.702055,125485696,18676288.0,6.718985,...,0.488281,0.800586,0.968262,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-104952...
2,CIFAR10,resnet56,GlobalCausalPruning,16,853018,57734,14.774968,125485696,7706240.0,16.283648,...,0.488477,0.733691,0.962793,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-111150...
11,CIFAR10,resnet56,GlobalCausalPruning,32,853018,31223,27.320181,125485696,4825472.0,26.004854,...,0.488281,0.722266,0.961328,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-113332...
6,CIFAR10,resnet56,GlobalCausalPruning,64,853018,17969,47.471646,125485696,1951232.0,64.311008,...,0.488281,0.628809,0.947363,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-115437...
7,CIFAR10,resnet56,GlobalMagWeight,2,853018,426509,2.000000,125485696,68716352.0,1.826140,...,0.973047,0.912891,0.974219,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-120048...
5,CIFAR10,resnet56,GlobalMagWeight,4,853018,213255,3.999991,125485696,39178560.0,3.202918,...,0.945508,0.907520,0.974707,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-120702...
1,CIFAR10,resnet56,GlobalMagWeight,8,853018,106628,7.999944,125485696,22508480.0,5.575041,...,0.643652,0.895215,0.974512,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-121316...
8,CIFAR10,resnet56,GlobalMagWeight,16,853018,53314,15.999887,125485696,12930688.0,9.704487,...,0.516797,0.868066,0.973730,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-121928...
4,CIFAR10,resnet56,GlobalMagWeight,32,853018,26657,31.999775,125485696,7275008.0,17.248874,...,0.488281,0.815430,0.969629,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-122541...
0,CIFAR10,resnet56,GlobalMagWeight,64,853018,13329,63.997149,125485696,3658176.0,34.302804,...,0.490918,0.702832,0.960254,42,256,100,SGD,0.001,101,final_results/results_resnet56/20251115-123154...

In [15]:
plot_df(df, 'compression', 'pre_acc5', markers='strategy', line='--', colors='strategy', suffix=' - pre')
plot_df(df, 'compression', 'post_acc5', markers='strategy', fig=False, colors='strategy')

In [16]:
plot_df(df, 'speedup', 'post_acc5', colors='strategy', markers='strategy')

In [17]:
df['compression_err'] = (df['real_compression'] - df['compression'])/df['compression']

In [18]:
plot_df(df, 'compression', 'compression_err', colors='strategy', markers='strategy')